# Generated by Django 5.1.7 on 2025-03-29 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('fastq_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('organism_name', models.CharField(blank=True, max_length=255, null=True)),
                ('library_prep_method_name', models.CharField(blank=True, max_length=255, null=True)),
                ('studies', models.JSONField(default=list)),
                ('alignment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('amplification_id', models.BigIntegerField(blank=True, null=True)),
                ('amplification_name', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_name_from_vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('cell_capture', models.IntegerField(blank=True, null=True)),
                ('cell_prep_type', models.CharField(blank=True, max_length=255, null=True)),
                ('library_prep_method_id', models.BigIntegerField(blank=True, null=True)),
                ('library_prep_name', models.CharField(blank=True, max_length=255, null=True)),
                ('organism_common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_id', models.BigIntegerField(blank=True, null=True)),
                ('sample_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sequencing_vendor', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'metadata',
            },
        ),
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('fastq_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='viewer.metadata')),
                ('status_id', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('fid', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'alignment',
            },
        ),
        migrations.CreateModel(
            name='Ingest',
            fields=[
                ('fastq_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='viewer.metadata')),
                ('status_id', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('fid', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'ingest',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('fastq_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='viewer.metadata')),
                ('study_set', models.CharField(blank=True, max_length=255, null=True)),
                ('organism', models.CharField(blank=True, max_length=255, null=True)),
                ('library_prep_method', models.CharField(blank=True, max_length=255, null=True)),
                ('alignment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('postqc_status', models.CharField(blank=True, max_length=50, null=True)),
                ('ingest_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'main',
            },
        ),
        migrations.CreateModel(
            name='PostQC',
            fields=[
                ('fastq_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='viewer.metadata')),
                ('status_id', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('fid', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'postqc',
            },
        ),
        migrations.CreateModel(
            name='LoadAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_name', models.CharField(default='', max_length=255)),
                ('fastq_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.metadata')),
            ],
            options={
                'db_table': 'load_association',
                'unique_together': {('fastq_name', 'load_name')},
            },
        ),
    ]
