# Generated by Django 5.1.7 on 2025-03-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='studies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
