# Generated by Django 5.1.7 on 2025-03-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_move_times_to_end_time'),
        ('viewer', 'move_times_to_end_time'),
    ]

    operations = [
    ]
