# Generated by Django 5.1.7 on 2025-04-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_add_metadata_toggles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'managed': False},
        ),
        migrations.AlterUniqueTogether(
            name='loadassociation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_alignment_method',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_amplification_id',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_amplification_name',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_batch_name_from_vendor',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_cell_prep_type',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_fastq_name',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_library_prep_method_id',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_library_prep_method_name',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_library_prep_name',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_organism_common_name',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_organism_name',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_sample_id',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_sample_name',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_sample_type',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_sequencing_vendor',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_studies',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='alignment',
            name='demand_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alignment',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postqc',
            name='demand_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postqc',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='fid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='status_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='fid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='status_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loadassociation',
            name='load_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postqc',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postqc',
            name='fid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postqc',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postqc',
            name='status_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='session_key',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='userpreferences',
            table='user_preferences',
        ),
    ]
