# Generated by Django 5.1.7 on 2025-04-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_main_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastq_name', models.CharField(max_length=255)),
                ('queue_type', models.CharField(choices=[('alignment', 'Alignment Queue'), ('postqc', 'Post-QC Queue')], max_length=20)),
                ('workflow', models.CharField(default='RTX', max_length=20)),
                ('command', models.TextField()),
                ('demand_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['fastq_name'], name='viewer_samp_fastq_n_310902_idx'), models.Index(fields=['queue_type', 'status'], name='viewer_samp_queue_t_181dfd_idx'), models.Index(fields=['demand_id'], name='viewer_samp_demand__8513e0_idx')],
            },
        ),
    ]
