# Generated by Django 5.1.7 on 2025-04-16 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_samplequeue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplequeue',
            options={'ordering': ['added_time']},
        ),
        migrations.RemoveIndex(
            model_name='samplequeue',
            name='viewer_samp_fastq_n_310902_idx',
        ),
        migrations.RemoveIndex(
            model_name='samplequeue',
            name='viewer_samp_queue_t_181dfd_idx',
        ),
        migrations.RemoveIndex(
            model_name='samplequeue',
            name='viewer_samp_demand__8513e0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='samplequeue',
            unique_together={('fastq_name', 'queue_type')},
        ),
        migrations.AlterField(
            model_name='samplequeue',
            name='added_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='samplequeue',
            name='command',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='samplequeue',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplequeue',
            name='workflow',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='samplequeue',
            name='end_time',
        ),
    ]
