# Generated by Django 5.1.7 on 2025-04-28 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_alter_samplequeue_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedJob',
            fields=[
                ('fastq_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('alignment_command', models.TextField()),
                ('postqc_command', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('alignment_attempts', models.IntegerField(default=0)),
                ('postqc_attempts', models.IntegerField(default=0)),
                ('alignment_demand_id', models.CharField(blank=True, max_length=255, null=True)),
                ('postqc_demand_id', models.CharField(blank=True, max_length=255, null=True)),
                ('alignment_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('postqc_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
            ],
            options={
                'db_table': 'completed_jobs',
            },
        ),
        migrations.CreateModel(
            name='FailedJob',
            fields=[
                ('fastq_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('alignment_command', models.TextField()),
                ('postqc_command', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('alignment_attempts', models.IntegerField(default=0)),
                ('postqc_attempts', models.IntegerField(default=0)),
                ('alignment_demand_id', models.CharField(blank=True, max_length=255, null=True)),
                ('postqc_demand_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'failed_jobs',
            },
        ),
        migrations.CreateModel(
            name='InProgressSamples',
            fields=[
                ('fastq_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('alignment_command', models.TextField(blank=True, null=True)),
                ('postqc_command', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('alignment_attempts', models.IntegerField(default=0)),
                ('postqc_attempts', models.IntegerField(default=0)),
                ('alignment_demand_id', models.CharField(blank=True, max_length=255, null=True)),
                ('postqc_demand_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'in_progress_samples',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('fastq_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('alignment_command', models.TextField(blank=True, null=True)),
                ('postqc_command', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'queue',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='RunningJob',
            fields=[
                ('fastq_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('alignment_command', models.TextField()),
                ('postqc_command', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('alignment_attempts', models.IntegerField(default=0)),
                ('postqc_attempts', models.IntegerField(default=0)),
                ('alignment_demand_id', models.CharField(blank=True, max_length=255, null=True)),
                ('postqc_demand_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'running_jobs',
            },
        ),
    ]
