# Generated by Django 5.1.7 on 2025-04-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_auto_20250428_1731'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='samplequeue',
            unique_together=set(),
        ),
        migrations.RenameModel(
            old_name='SampleQueue',
            new_name='QueueJobs',
        ),
        migrations.AlterModelTable(
            name='QueueJobs',
            table='queue_jobs',
        ),
    ]
