# Generated by Django 5.1.7 on 2025-04-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_update_samplequeue_primary_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuejobs',
            name='id',
        ),
        migrations.AlterField(
            model_name='queuejobs',
            name='fastq_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
