# Generated by Django 5.2.17 on 2026-08-15 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[("align", "Alignment"), ("post-align", "Post-alignment")], max_length=20
                    ),
                ),
                ("modality", models.CharField(max_length=20)),
                (
                    "modality_source",
                    models.CharField(
                        choices=[
                            ("inferred", "Inferred from batch name"),
                            ("user_confirmed", "Chosen and confirmed by user"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notify_email", models.EmailField(max_length=254)),
                ("batch_processing", models.BooleanField(default=False)),
                ("forced", models.BooleanField(default=False)),
                ("command_args", models.JSONField()),
                ("command", models.TextField()),
                (
                    "spacing",
                    models.PositiveIntegerField(help_text="Seconds to wait before the next submission"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUBMITTING", "Submitting"),
                            ("SUBMITTED", "Submitted"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("demand_id", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="queue_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to="catalog.sample",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="queueing_qu_status_1b974c_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("sample", "stage"),
                        name="one_pending_entry_per_sample_stage",
                    )
                ],
            },
        ),
    ]
