# Generated by Django 5.2.17 on 2026-08-15 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('queueing', '0002_queueentry_claimed_at_alter_queueentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='catalog.sample'),
        ),
    ]
