# Generated by Django 5.2.17 on 2026-08-16 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_sample_batch_prefix_alter_sample_modality'),
        ('queueing', '0003_alter_queueentry_sample'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.sample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added_at', 'id'],
                'indexes': [models.Index(fields=['user', 'added_at'], name='queueing_ca_user_id_513caf_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'sample'), name='one_cart_item_per_user_sample')],
            },
        ),
    ]
