# Generated by Django 5.1.7 on 2025-05-27 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Main",
            fields=[
                (
                    "fastq_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="main",
                        serialize=False,
                        to="ocs.metadata",
                    ),
                ),
                ("study_set", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "library_prep_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("organism", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "alignment_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "postqc_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "ingest_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "main",
                "managed": False,
            },
        ),
    ]
