# Generated by Django 5.1.7 on 2025-05-27 19:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Metadata",
            fields=[
                (
                    "fastq_name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "organism_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "library_prep_method_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("studies", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "alignment_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("amplification_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "amplification_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("batch_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "batch_name_from_vendor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cell_capture", models.IntegerField(blank=True, null=True)),
                (
                    "cell_prep_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "library_prep_method_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "library_prep_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "organism_common_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sample_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "sample_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sample_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sequencing_vendor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "metadata",
            },
        ),
        migrations.CreateModel(
            name="CompletedJob",
            fields=[
                (
                    "fastq_name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("alignment_command", models.TextField()),
                ("postqc_command", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("alignment_attempts", models.IntegerField(default=0)),
                ("postqc_attempts", models.IntegerField(default=0)),
                (
                    "alignment_demand_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "postqc_demand_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "alignment_status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                (
                    "postqc_status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("alignment_start_time", models.DateTimeField(blank=True, null=True)),
                ("alignment_end_time", models.DateTimeField(blank=True, null=True)),
                ("postqc_start_time", models.DateTimeField(blank=True, null=True)),
                ("postqc_end_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "completed_jobs",
            },
        ),
        migrations.CreateModel(
            name="FailedJob",
            fields=[
                (
                    "fastq_name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("alignment_command", models.TextField()),
                ("postqc_command", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("alignment_attempts", models.IntegerField(default=0)),
                ("postqc_attempts", models.IntegerField(default=0)),
                (
                    "alignment_demand_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "postqc_demand_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "failed_jobs",
            },
        ),
        migrations.CreateModel(
            name="InProgressSamples",
            fields=[
                (
                    "fastq_name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("alignment_command", models.TextField(blank=True, null=True)),
                ("postqc_command", models.TextField(blank=True, null=True)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                ("alignment_attempts", models.IntegerField(default=0)),
                ("postqc_attempts", models.IntegerField(default=0)),
                (
                    "alignment_demand_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "postqc_demand_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "in_progress_samples",
                "ordering": ["-time"],
            },
        ),
        migrations.CreateModel(
            name="QueueJobs",
            fields=[
                (
                    "fastq_name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("alignment_command", models.TextField(blank=True, null=True)),
                ("postqc_command", models.TextField(blank=True, null=True)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Ready", "Ready"),
                            ("Running", "Running"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Ready",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "queue_jobs",
                "ordering": ["-time"],
            },
        ),
        migrations.CreateModel(
            name="RunningJob",
            fields=[
                (
                    "fastq_name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("alignment_command", models.TextField()),
                ("postqc_command", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("alignment_attempts", models.IntegerField(default=0)),
                ("postqc_attempts", models.IntegerField(default=0)),
                (
                    "alignment_demand_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "postqc_demand_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "running_jobs",
            },
        ),
        migrations.CreateModel(
            name="Alignment",
            fields=[
                (
                    "fastq_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="ocs.Metadata",
                    ),
                ),
                ("status_id", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("fid", models.CharField(blank=True, max_length=255, null=True)),
                ("demand_id", models.CharField(blank=True, max_length=255, null=True)),
                ("retry_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "alignment",
            },
        ),
        migrations.CreateModel(
            name="Ingest",
            fields=[
                (
                    "fastq_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="ocs.Metadata",
                    ),
                ),
                ("status_id", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("fid", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "ingest",
            },
        ),
        migrations.CreateModel(
            name="PostQC",
            fields=[
                (
                    "fastq_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="ocs.Metadata",
                    ),
                ),
                ("status_id", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("fid", models.CharField(blank=True, max_length=255, null=True)),
                ("demand_id", models.CharField(blank=True, max_length=255, null=True)),
                ("retry_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "postqc",
            },
        ),
        migrations.CreateModel(
            name="LoadAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("load_name", models.CharField(max_length=255)),
                (
                    "fastq_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ocs.Metadata",
                    ),
                ),
            ],
            options={
                "db_table": "load_association",
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("show_batch_name", models.BooleanField(default=True)),
                ("show_cell_capture", models.BooleanField(default=True)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="light",
                        max_length=10,
                    ),
                ),
                (
                    "column_settings",
                    models.JSONField(
                        default=dict, help_text="Column visibility preferences"
                    ),
                ),
                (
                    "filter_preferences",
                    models.JSONField(default=dict, help_text="Default filter settings"),
                ),
                (
                    "default_filter_mode",
                    models.CharField(
                        choices=[
                            ("realtime", "Real-time"),
                            ("manual", "Manual"),
                            ("server-side", "Server-side"),
                        ],
                        default="realtime",
                        max_length=20,
                    ),
                ),
                (
                    "default_page_size",
                    models.IntegerField(
                        choices=[
                            (10, "10 per page"),
                            (25, "25 per page"),
                            (50, "50 per page"),
                            (100, "100 per page"),
                        ],
                        default=25,
                    ),
                ),
                ("auto_refresh_enabled", models.BooleanField(default=False)),
                (
                    "auto_refresh_interval",
                    models.IntegerField(default=30, help_text="Seconds"),
                ),
                ("advanced_filters_open", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated user for authenticated sessions",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_preferences",
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("page_url", models.URLField()),
                ("action", models.CharField(max_length=50)),
                ("details", models.JSONField(default=dict)),
                (
                    "load_time",
                    models.FloatField(
                        blank=True, help_text="Page load time in seconds", null=True
                    ),
                ),
                (
                    "data_size",
                    models.IntegerField(
                        blank=True, help_text="Data size in bytes", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_activity",
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="user_activi_user_id_ca8c85_idx",
                    ),
                    models.Index(
                        fields=["session_key", "-timestamp"],
                        name="user_activi_session_009223_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="user_activi_action_63dd9f_idx",
                    ),
                ],
            },
        ),
    ]
