# Generated by Django 5.1.7 on 2025-05-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocs", "0002_metadata_completedjob_failedjob_inprogresssamples_and_more"),
    ]

    operations = []
