# Generated by Django 5.1.7 on 2025-05-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocs", "0003_auto_20250527_2019"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "paused",
                    models.BooleanField(
                        default=False, help_text="Whether queue processing is paused"
                    ),
                ),
                (
                    "processing_interval",
                    models.IntegerField(
                        default=180, help_text="Processing interval in seconds"
                    ),
                ),
                (
                    "capacity_limit",
                    models.IntegerField(default=6, help_text="Maximum concurrent jobs"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auto_processing_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable automatic processing"
                    ),
                ),
                (
                    "last_processed_at",
                    models.DateTimeField(
                        blank=True, help_text="Last time a job was processed", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Settings",
                "verbose_name_plural": "Queue Settings",
                "db_table": "queue_settings",
            },
        ),
        migrations.AlterField(
            model_name="completedjob",
            name="alignment_command",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="completedjob",
            name="postqc_command",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="failedjob",
            name="alignment_command",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="failedjob",
            name="postqc_command",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="runningjob",
            name="alignment_command",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="runningjob",
            name="postqc_command",
            field=models.TextField(blank=True, null=True),
        ),
    ]
