# Generated by Django 5.1.7 on 2025-06-02 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocs", "0004_add_queue_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQueueSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=128, unique=True)),
                ("timer_active", models.BooleanField(default=False)),
                ("timer_paused", models.BooleanField(default=False)),
                (
                    "timer_next_process_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("timer_auto_process_interval", models.IntegerField(default=180000)),
                (
                    "timer_paused_time_remaining",
                    models.IntegerField(blank=True, null=True),
                ),
                ("queue_auto_refresh_interval", models.IntegerField(default=30000)),
                ("queue_rows_per_page", models.IntegerField(default=10)),
                ("queue_auto_refresh_enabled", models.BooleanField(default=False)),
                ("queue_current_page", models.IntegerField(default=1)),
                ("queue_filter_state", models.JSONField(blank=True, default=dict)),
                ("queue_sort_state", models.JSONField(blank=True, default=dict)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("device_fingerprint", models.CharField(blank=True, max_length=64)),
                ("browser_info", models.CharField(blank=True, max_length=255)),
                ("jobs_processed", models.IntegerField(default=0)),
                ("session_duration", models.IntegerField(default=0)),
                ("last_job_processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_queue_sessions",
            },
        ),
        migrations.DeleteModel(
            name="QueueSettings",
        ),
        migrations.RemoveField(
            model_name="completedjob",
            name="time",
        ),
        migrations.AddIndex(
            model_name="userqueuesession",
            index=models.Index(fields=["user"], name="user_queue__user_id_a712ba_idx"),
        ),
        migrations.AddIndex(
            model_name="userqueuesession",
            index=models.Index(
                fields=["session_key"], name="user_queue__session_6836e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userqueuesession",
            index=models.Index(
                fields=["last_activity"], name="user_queue__last_ac_7dfdb8_idx"
            ),
        ),
    ]
