# Generated by Django 5.1.7 on 2025-06-02 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocs", "0005_userqueuesession_delete_queuesettings_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTimerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_process_time",
                    models.IntegerField(
                        default=180000,
                        help_text="Auto process interval in milliseconds",
                    ),
                ),
                (
                    "next_process_time",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Next processing time (timestamp)",
                        null=True,
                    ),
                ),
                ("is_paused", models.BooleanField(default=False)),
                (
                    "paused_time_remaining",
                    models.IntegerField(
                        blank=True,
                        help_text="Remaining time when paused (ms)",
                        null=True,
                    ),
                ),
                ("jobs_processed", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timer_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_timer_state",
            },
        ),
        migrations.DeleteModel(
            name="UserQueueSession",
        ),
        migrations.AddIndex(
            model_name="usertimerstate",
            index=models.Index(
                fields=["user", "-last_update"], name="user_timer__user_id_edec24_idx"
            ),
        ),
    ]
