# Generated by Django 5.1.7 on 2025-06-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocs", "0006_usertimerstate_delete_userqueuesession_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="main",
            options={"managed": False, "ordering": ["fastq_name"]},
        ),
        migrations.AlterField(
            model_name="completedjob",
            name="alignment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                    ("Cancelled", "Cancelled"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="completedjob",
            name="postqc_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                    ("Cancelled", "Cancelled"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="queuejobs",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ready", "Ready"),
                    ("Pending", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("Running", "Running"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Ready",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="UserTimerState",
        ),
    ]
