# Generated by Django 5.1.15 on 2026-06-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocs', '0007_remove_completed_job_status_defaults'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InProgressSamples',
        ),
        migrations.AlterField(
            model_name='queuejobs',
            name='status',
            field=models.CharField(default='Ready', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
