# Generated by Django 5.1.15 on 2026-06-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocs', '0011_userpreferences_per_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='batch_name',
        ),
    ]
