# Generated by Django 5.2.17 on 2026-08-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='alignment_method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sample',
            name='amplification_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='amplification_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sample',
            name='batch_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sample',
            name='cell_capture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='cell_prep_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sample',
            name='library_prep_method_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='library_prep_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sample',
            name='organism_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sample',
            name='sequencing_vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='library_prep_method_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='organism_common_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
