# Generated by Django 5.2.17 on 2026-08-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_stagestatus_file_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagestatus',
            name='stage',
            field=models.CharField(choices=[('ingest', 'Ingest'), ('align', 'Alignment'), ('post-align', 'Post-alignment'), ('export', 'Export')], max_length=20),
        ),
    ]
