# Generated by Django 5.2.17 on 2026-08-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    # Plain AddIndex, which takes an ACCESS EXCLUSIVE lock for the length of the build.
    # AddIndexConcurrently would avoid that, but it needs 'django.contrib.postgres' in
    # INSTALLED_APPS and it is not there. On a table this size, run this during a window
    # where a brief write lock on catalog_stagestatus is acceptable.

    dependencies = [
        ('catalog', '0008_alter_stagestatus_stage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stagestatus',
            index=models.Index(fields=['stage', 'status'], name='catalog_sta_stage_c0b808_idx'),
        ),
    ]
