# Generated by Django 5.2.17 on 2026-08-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_stagestatus_catalog_sta_stage_c0b808_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sample',
            name='catalog_sam_modalit_b48048_idx',
        ),
    ]
