# Generated by Django 5.2.17 on 2026-08-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_remove_sample_catalog_sam_modalit_b48048_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sample",
            name="catalog_sam_load_na_e24f20_idx",
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(fields=["load_name", "batch_prefix"], name="catalog_sam_load_na_bd6c5a_idx"),
        ),
    ]
