# Generated by Django 5.2.17 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_remove_sample_catalog_sam_load_na_e24f20_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagestatus",
            name="execution_arn",
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddIndex(
            model_name="stagestatus",
            index=models.Index(fields=["demand_id"], name="catalog_sta_demand__817df3_idx"),
        ),
    ]
