# Generated by Django 5.2.17 on 2026-08-15 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fastq_name", models.CharField(max_length=255, unique=True)),
                ("batch_name_from_vendor", models.CharField(db_index=True, max_length=255)),
                ("load_name", models.CharField(blank=True, max_length=255)),
                ("library_prep_method_name", models.CharField(max_length=255)),
                ("organism_common_name", models.CharField(max_length=255)),
                ("sample_names", models.JSONField(default=list)),
                ("studies", models.JSONField(default=list)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["fastq_name"],
            },
        ),
        migrations.CreateModel(
            name="StageStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("ingest", "Ingest"),
                            ("align", "Alignment"),
                            ("post-align", "Post-alignment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("demand_id", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(max_length=32)),
                ("last_update_time", models.DateTimeField(blank=True, null=True)),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_statuses",
                        to="catalog.sample",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("sample", "stage"), name="unique_stage_per_sample")
                ],
            },
        ),
    ]
