# Generated by Django 5.2.17 on 2026-08-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_sample_alignment_method_sample_amplification_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagestatus',
            name='synced_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
