# Generated by Django 5.2.17 on 2026-08-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_stagestatus_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='batch_prefix',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(batch_name_from_vendor__startswith='MTX', then=models.Value('MTX')), models.When(batch_name_from_vendor__startswith='RFX', then=models.Value('RFX')), models.When(batch_name_from_vendor__startswith='ATX', then=models.Value('ATX')), default=models.Value('RTX')), output_field=models.CharField(choices=[('MTX', 'MTX'), ('RFX', 'RFX'), ('ATX', 'ATX'), ('RTX', 'RTX')], max_length=3)),
        ),
        migrations.AddField(
            model_name='sample',
            name='modality',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(batch_name_from_vendor__startswith='RFX', then=models.Value('RFX')), models.When(batch_name_from_vendor__startswith='MTX', then=models.Value('MTX')), models.When(batch_name_from_vendor__startswith='ATX', then=models.Value('MTX')), default=models.Value('RTX')), output_field=models.CharField(choices=[('MTX', 'MTX'), ('RFX', 'RFX'), ('RTX', 'RTX')], max_length=3)),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['batch_prefix'], name='catalog_sam_batch_p_6c40a3_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['modality'], name='catalog_sam_modalit_b48048_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['load_name', 'library_prep_method_name'], name='catalog_sam_load_na_e24f20_idx'),
        ),
    ]
