# Generated by Django 5.2.17 on 2026-08-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_sample_batch_prefix_alter_sample_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagestatus',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagestatus',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
