# Generated by Django 5.2.17 on 2026-08-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_stagestatus_duration_seconds_stagestatus_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagestatus',
            name='file_store_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
