# Generated by Django 5.2.17 on 2026-08-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTING', 'Submitting'), ('SUBMITTED', 'Submitted'), ('FAILED', 'Failed'), ('STRANDED', 'Stranded — check OCS before requeueing'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
