# Generated by Django 5.2.17 on 2026-08-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("queueing", "0004_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUBMITTING", "Submitting"),
                    ("SUBMITTED", "Submitted"),
                    ("FAILED", "Failed"),
                    ("STRANDED", "Stranded. Check OCS before requeueing"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
