# Generated by Django 5.2.17 on 2026-08-17 11:20

from django.db import migrations, models


def convert_stranded_to_failed(apps, schema_editor):
    QueueEntry = apps.get_model("queueing", "QueueEntry")
    QueueEntry.objects.filter(status="STRANDED").update(status="FAILED")


class Migration(migrations.Migration):
    dependencies = [
        ("queueing", "0005_alter_queueentry_status"),
    ]

    operations = [
        migrations.RunPython(convert_stranded_to_failed, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="queueentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUBMITTING", "Submitting"),
                    ("SUBMITTED", "Submitted"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
