# Generated by Django 5.2.17 on 2026-08-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0006_alter_queueentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUBMITTING', 'SUBMITTING'), ('SUBMITTED', 'SUBMITTED'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20),
        ),
    ]
